### ISSUE TITLE
How to adjust Scrolling time?

### ISSUE THREAD

**Issue by SuYungCheng** [MaorS/iOS-Proj-CasinoGame#1]
When I tap the bar to scroll casino.
It stop very short time, about 1 second.
How can I adjust the time scrolling?
Thanks!

**Comment by MaorS** [comment]
Please read this https://stackoverflow.com/questions/43740187/how-do-i-decrease-the-speed-in-which-a-row-is-selected-in-a-pickerview

**Comment by GUdokermensz** [comment]
> Please read this https://stackoverflow.com/questions/43740187/how-do-i-decrease-the-speed-in-which-a-row-is-selected-in-a-pickerview
